version: "3.8"

services:
  # The backend instance
  # TODO update ps name to the initials of ur project
  asg:
    build: .
    ports:
      - 8080:8080
    env_file: Tiktok_Analytics/.env
    environment:
      HOST: "0.0.0.0"
      PORT: "8080"
    command:
    
      - "ASG"
    networks:
      - dev
    depends_on:
      - "db"
      - "mongodb"


  # Database instance
  db:
    image: postgres:13-alpine
    hostname: db
    env_file: Tiktok_Analytics/.env
    networks:
      - dev
  mongodb:
    image: mongo:4.2.8
    hostname: mongodb
    env_file: Tiktok_Analytics/.env
    networks:
      - dev
    volumes:
      - ./Tiktok_Analytics/mongodb:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    env_file: Tiktok_Analytics/.env
    networks:
      - dev
networks:
  dev:
